use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :call_sync, CallSync.Endpoint,
  http: [:inet6, port: {:system, "PORT"}],
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

# Update secret
config :call_sync, update_secret: "${UPDATE_SECRET}"

config :call_sync,
  mongodb_username: "${MONGO_USERNAME}",
  mongodb_seeds: ["${MONGO_SEED_1}", "${MONGO_SEED_2}"],
  mongodb_password: "${MONGO_PASSWORD}",
  mongodb_port: "${MONGO_PORT}"

config :rollbax,
  access_token: "${ROLLBAR_ACCESS_TOKEN}",
  environment: "production"

config :call_sync,
  airtable_key: "${AIRTABLE_KEY}",
  airtable_base: "${AIRTABLE_BASE}",
  airtable_table_name: "${AIRTABLE_TABLE_NAME}",
  secret: "${UPDATE_SECRET}"

config :call_sync,
  lv_access_token: "${LIVEVOX_ACCESS_TOKEN}",
  lv_clientname: "${LIVEVOX_CLIENT_NAME}",
  lv_username: "${LIVEVOX_USERNAME}",
  lv_password: "${LIVEVOX_PASSWORD}"

config :call_sync,
  aws_bucket_name: System.get_env("AWS_BUCKET_NAME"),
  zapier_hook_url: System.get_env("ZAPIER_HOOK_URL"),
  second_zapier_hook_url: System.get_env("SECOND_ZAPIER_HOOK_URL")

config :ex_aws,
  access_key_id: ["${AWS_ACCESS_KEY_ID}", :instance_role],
  secret_access_key: ["${AWS_SECRET_ACCESS_KEY}", :instance_role]

config :call_sync, application_name: "${VAN_APP_NAME}"
